-- AtmoSync Raw IoT Tables
-- Prakruthi - Day 1

USE DATABASE ATMOSYNC_DB;
USE SCHEMA RAW;

CREATE TABLE IF NOT EXISTS CONTAINER_TELEMETRY (
    EVENT_ID VARCHAR,
    CONTAINER_ID VARCHAR,
    EVENT_TIMESTAMP TIMESTAMP,
    TEMPERATURE FLOAT,
    HUMIDITY FLOAT,
    VIBRATION FLOAT
);