-- AtmoSync Raw Data Access Roles
-- Prakruthi - Day 1

CREATE ROLE IF NOT EXISTS ATMOSYNC_RAW_READER;

GRANT USAGE ON DATABASE ATMOSYNC_DB
TO ROLE ATMOSYNC_RAW_READER;

GRANT USAGE ON SCHEMA ATMOSYNC_DB.RAW
TO ROLE ATMOSYNC_RAW_READER;

GRANT SELECT ON ALL TABLES IN SCHEMA ATMOSYNC_DB.RAW
TO ROLE ATMOSYNC_RAW_READER;