select current_user();
CREATE WAREHOUSE ATMOSYNC_WH
WITH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE;

    USE WAREHOUSE ATMOSYNC_WH;
    CREATE DATABASE ATMOSYNC_DB;
    USE DATABASE ATMOSYNC_DB; 
    CREATE SCHEMA ATMOSYNC_DB.RAW;

CREATE SCHEMA ATMOSYNC_DB.STAGING;

CREATE SCHEMA ATMOSYNC_DB.ANALYTICS;

CREATE TABLE ATMOSYNC_DB.RAW.RAW_TELEMETRY (
    telemetry_id VARCHAR,
    received_at TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    payload VARIANT
);

CREATE TABLE ATMOSYNC_DB.RAW.COMMODITY_PRICES (
    commodity VARCHAR,
    market VARCHAR,
    price_per_kg FLOAT,
    updated_at TIMESTAMP_NTZ
);

INSERT INTO ATMOSYNC_DB.RAW.COMMODITY_PRICES
(commodity, market, price_per_kg, updated_at)
VALUES
('Avocado', 'Bangalore', 180, CURRENT_TIMESTAMP()),
('Avocado', 'Pune', 195, CURRENT_TIMESTAMP()),
('Avocado', 'Mumbai', 210, CURRENT_TIMESTAMP()),
('Banana', 'Bangalore', 70, CURRENT_TIMESTAMP()),
('Banana', 'Pune', 75, CURRENT_TIMESTAMP()),
('Banana', 'Mumbai', 82, CURRENT_TIMESTAMP());

CREATE ROLE ATMOSYNC_ROLE;
GRANT USAGE ON DATABASE ATMOSYNC_DB
TO ROLE ATMOSYNC_ROLE;

GRANT USAGE ON SCHEMA ATMOSYNC_DB.RAW
TO ROLE ATMOSYNC_ROLE;

GRANT USAGE ON SCHEMA ATMOSYNC_DB.STAGING
TO ROLE ATMOSYNC_ROLE;

GRANT USAGE ON SCHEMA ATMOSYNC_DB.ANALYTICS
TO ROLE ATMOSYNC_ROLE;